# Generated by Django 4.2.13 on 2024-05-26 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='QrCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qrcodes/')),
                ('url_image', models.URLField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='basic_app.files')),
            ],
            options={
                'verbose_name': 'QrCode',
                'verbose_name_plural': 'QrCodes',
            },
        ),
    ]
